<?php
$urlBASE="myProject/";
define("dirPAGE","http://{$_SERVER['HTTP_HOST']}/{$urlBASE}");
define("dirREQ","{$_SERVER['DOCUMENT_ROOT']}/{$urlBASE}");
define("dirCSS",dirPAGE."public/css");
define("dirJS",dirPAGE."public/js");
define("dirIMG",dirPAGE."public/img");
define("dirCRUD",dirPAGE."src/crud");
define("dirVENDOR",dirPAGE."public/vendor");
define("dirMANIPULACAO",dirREQ."src/Manipulacao");
define("dirFORM",dirPAGE."src/Page/formulario");
define("dirINCLUDE",dirREQ."src/include");
define("dirMODEL",dirREQ."src/models");
define("dirSRC",dirPAGE."src");
define("dirUPLOAD",dirREQ."src/crud/uploads");

define("_dirCSS",dirREQ."src/public/css/");
define("_dirJS",dirREQ."src/public/js/");
define("_dirIMG",dirREQ."src/public/img/");
define("_dirCRUD",dirREQ."src/crud/");
define("_dirVENDOR",dirREQ."src/public/vendor/");
define("_dirMANIPULACAO",dirREQ."src/Manipulacao/");
define("_dirFORM",dirREQ."src/Page/formulario/");
define("_dirINCLUDE",dirREQ."src/include/");
define("_dirMODEL",dirREQ."src/models/");
define("_dirSRC",dirREQ."src/");
define("_dirUPLOAD",dirREQ."src/crud/uploads/");